Models/JournalEntry.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace AccountingApp.Models
{
    public class JournalEntry
    {
        public int Id { get; set; }
        public int JournalId { get; set; }
        public Company Company { get; set; }
        public AccountingYear AccountingYear { get; set; }
        public DateTime Date { get; set; }
        public List<LedgerEntry> Rows { get; set; }
        public bool Active { get; set; }
        public string Name { get; set; }
    }
}

ViewModels/ExportViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccountingApp.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AccountingApp.ViewModels
{
    public class ExportViewModel
    {
        public int CompanyId { get; set; }
        public List<SelectListItem> AccountingYearsSelectListItems { get; set; }
        public string SelectedAccountingYear { get; set; }
       
    }
}

ViewModels/JournalEntryViewModel.cs
using AccountingApp.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AccountingApp.ViewModels
{
    public class JournalEntryViewModel
    {
        public Company Company { get; set; }
        public Dictionary<int, string> Accounts { get; set; }
        public List<AccountingYear> AccountingYears { get; set; }
        public List<SelectListItem> AccountingYearsList { get; set; }
        public string SelectedAccountingYear { get; set; }
        public DateTime SelectedAccountingYearStartDate { get; set; }
        public DateTime SelectedAccountingYearEndDate { get; set; }
        public DateTime SelectedDate { get; set; }
        public List<SelectListItem> JournalsList { get; set; }
        public string SelectedJournal { get; set; }
        public JournalViewModelRow[] Rows { get; set; }
        public int RowsUsed { get; set; }
        public string Text { get; set; }

    }

    public class JournalViewModelRow
    {
        public string AccountNumber { get; set; }
        public double Credit { get; set; }
        public double Debit { get; set; }

    }
}

ViewModels/ReportViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccountingApp.Models;

namespace AccountingApp.ViewModels
{
    public class ReportViewModel
    {

        public List<AccountingYear> Years { get; set; }
      
        public List<Account> Accounts { get; set; }
       
        //Key - accountingyearid, value - YearReport
        public Dictionary<AccountingYear, YearReport> Reports { get; set; }
       
    }

    public class YearReport
    {
        //key - account number, value  - sum      
       public Dictionary<Account, List<LedgerEntry>> LedgerEntriesPerAccount { get; set; }
    }
}

ViewModels/SubmitViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AccountingApp.ViewModels
{
    public class SubmitViewModel
    {
        public int? JournalEntryId { get; set; }
        public int? CompanyId { get; set; }
        public string Status { get; set; }
    }
}

Controllers/JournalEntriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AccountingApp.Data;
using AccountingApp.Models;
using Microsoft.AspNetCore.Authorization;
using AccountingApp.ViewModels;
using Microsoft.AspNetCore.StaticFiles;
using System.Text;

namespace AccountingApp.Controllers
{
    [Authorize]
    public class JournalEntriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public JournalEntriesController(ApplicationDbContext context)
        {
            _context = context;
        }
        //TODO: Limit to accounting year
        //TODO: Move companyId to session
        [Route("JournalEntries/Index/{companyId}")]
        // GET: JournalEntries
        public async Task<IActionResult> Index(int companyId)
        {
            ViewBag.companyId = companyId;
            List<JournalEntry> journalEntries = await _context.JournalEntry.Where(je => je.Company.Id == companyId).OrderBy(je => je.Date).ToListAsync();
            List<JournalEntriesListViewModel> journalEntriesListViewModels = new List<JournalEntriesListViewModel>();
            foreach (JournalEntry je in journalEntries)
            {
                JournalEntriesListViewModel currentJournalEntry = new JournalEntriesListViewModel { JournalEntry = je, CreditSum = 0, DebitSum = 0, Rows = new List<JournalEntriesListViewModelRow>() };
                List<LedgerEntry> currentRows = await _context.LedgerEntries.Where(le => le.JournalEntryId == je.Id).ToListAsync();
                foreach (LedgerEntry le in currentRows)
                {
                    double debit = (le.Value >= 0) ? Math.Abs(le.Value) : 0;
                    double credit = (le.Value >= 0) ? 0 : Math.Abs(le.Value);

                    currentJournalEntry.DebitSum += debit;
                    currentJournalEntry.CreditSum += credit;

                    Account account = await _context.Accounts.FindAsync(le.AccountId);


                    currentJournalEntry.Rows.Add(new JournalEntriesListViewModelRow { AccountName = account.Name, AccountNumber = account.AccountNumber, Debit = debit, Credit = credit });
                }
                journalEntriesListViewModels.Add(currentJournalEntry);
            }
            return View(journalEntriesListViewModels);
        }

        // GET: JournalEntries/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var journalEntry = await _context.JournalEntry
                .FirstOrDefaultAsync(m => m.Id == id);
            if (journalEntry == null)
            {
                return NotFound();
            }

            JournalEntriesDetailViewModel journalEntriesDetailViewModel = new JournalEntriesDetailViewModel();
            journalEntriesDetailViewModel.JournalEntry = journalEntry;
            journalEntriesDetailViewModel.Rows = new List<JournalEntriesDetailViewModelRow>();
            await _context.Entry(journalEntry).Collection(je => je.Rows).LoadAsync();

            foreach (LedgerEntry le in journalEntry.Rows)
            {
                double debit = (le.Value >= 0) ? Math.Abs(le.Value) : 0;
                double credit = (le.Value >= 0) ? 0 : Math.Abs(le.Value);

                journalEntriesDetailViewModel.DebitSum += debit;
                journalEntriesDetailViewModel.CreditSum += credit;

                Account account = await _context.Accounts.FindAsync(le.AccountId);


                journalEntriesDetailViewModel.Rows.Add(new JournalEntriesDetailViewModelRow { AccountName = account.Name, AccountNumber = account.AccountNumber, Debit = debit, Credit = credit });
            }

            return View(journalEntriesDetailViewModel);
        }
        [Route("JournalEntries/Create/{CompanyId}")]
        public async Task<IActionResult> Create(int CompanyId)
        {
            Company company = await _context.Companies.FindAsync(CompanyId);

            //Build selectlist for accounting year
            List<AccountingYear> years = await _context.AccountingYears.Where(ay => ay.CompanyId == company.Id).OrderByDescending(ay => ay.StartDate).ToListAsync();
            List<SelectListItem> yearList = GetAccountingYearSelectList(company.Id);


            //Build dictionary for accounts
            List<Account> accounts = await _context.Accounts.Where(a => a.CompanyId == company.Id).OrderBy(a => a.AccountNumber).ToListAsync();
            Dictionary<int, string> accountDict = new Dictionary<int, string>();
            foreach (Account a in accounts)
            {
                accountDict.Add(a.AccountNumber, a.Name);
            }
            //Build selectlist for journals
            List<Journal> Journals = await _context.Journals.Where(j => j.CompanyId == CompanyId).ToListAsync();
            List<SelectListItem> journals = new List<SelectListItem>();
            foreach (Journal j in Journals)
            {
                journals.Add(new SelectListItem { Value = j.Id.ToString(), Text = j.Name });
            }

            //Return view with model
            return View(new JournalEntryViewModel
            {
                Company = company,
                Accounts = accountDict,
                SelectedAccountingYear = years.First().Id.ToString(),
                SelectedAccountingYearStartDate = years.First().StartDate,
                SelectedAccountingYearEndDate = years.First().EndDate,
                AccountingYears = years,
                AccountingYearsList = yearList,
                JournalsList = journals,
                Rows = new JournalViewModelRow[100]  //Prepare a list to hold rows
            });
        }
        [HttpPost]
        [Route("JournalEntries/Create/{CompanyId}")]
        public async Task<IActionResult> Create(int CompanyId, JournalEntryViewModel model)
        {
            //Load company, accountingyear, journal
            Company company = await _context.Companies.FindAsync(CompanyId);
            AccountingYear accountingYear = await _context.AccountingYears.FindAsync(int.Parse(model.SelectedAccountingYear));
            Journal journal = await _context.Journals.FindAsync(int.Parse(model.SelectedJournal));
            await _context.Entry(journal).Collection(j => j.JournalEntries).LoadAsync();

            //Create journalentry & ledgerentries            
            JournalEntry journalEntry = new JournalEntry { Company = company, AccountingYear = accountingYear, Date = model.SelectedDate, Active = true, Rows = new List<LedgerEntry>(), Name = model.Text };
            journal.JournalEntries.Add(journalEntry);

            //Loop over each row and add to JournalEntry
            for (int i = 0; i < model.RowsUsed; i++)
            {
                int accountNumber = int.Parse(model.Rows[i].AccountNumber);
                Account account = await _context.Accounts.Where(a => a.CompanyId == company.Id && a.AccountNumber == accountNumber).FirstAsync();
                //Set account to used if not
                if (!account.Used)
                    account.Used = true;

                journalEntry.Rows.Add(new LedgerEntry { JournalEntryId = journal.Id, AccountId = account.Id, Value = (model.Rows[i].Debit - model.Rows[i].Credit), Active = true });
            }
            await _context.SaveChangesAsync();
            SubmitViewModel submitViewModel = new SubmitViewModel { JournalEntryId = journalEntry.Id, CompanyId = company.Id, Status = "Success!" };
            return RedirectToAction("Submit", submitViewModel);
        }

        [Route("JournalEntries/Submit")]
        public async Task<IActionResult> Submit(SubmitViewModel model)
        {
            return View(model);
        }

        //TODO: Fix loading LedgerEntry into rows
        [Route("JournalEntries/Edit/{JournalEntryId}")]
        public async Task<IActionResult> Edit(int JournalEntryId)
        {

            JournalEntry journalEntry = await _context.JournalEntry.Include(je => je.Company).FirstAsync(je => je.Id == JournalEntryId);
            Company company = journalEntry.Company;

            //Build selectlist for accounting year
            List<SelectListItem> yearList = GetAccountingYearSelectList(company.Id);
            AccountingYear startYear = await _context.AccountingYears.Where(ay => ay.Id.ToString() == yearList.First().Value).FirstAsync();
            List<AccountingYear> years = await _context.AccountingYears.Where(ay => ay.CompanyId == company.Id).OrderByDescending(ay => ay.StartDate).ToListAsync();

            //Build dictionary for accounts
            List<Account> accounts = await _context.Accounts.Where(a => a.CompanyId == company.Id).OrderBy(a => a.AccountNumber).ToListAsync();
            Dictionary<int, string> accountDict = new Dictionary<int, string>();
            foreach (Account a in accounts)
            {
                accountDict.Add(a.AccountNumber, a.Name);
            }

            //Build selectlist for journals
            List<Journal> Journals = await _context.Journals.Where(j => j.CompanyId == company.Id).ToListAsync();
            List<SelectListItem> journals = new List<SelectListItem>();
            foreach (Journal j in Journals)
            {
                journals.Add(new SelectListItem { Value = j.Id.ToString(), Text = j.Name });
            }

            JournalViewModelRow[] rows = new JournalViewModelRow[100];
            List<LedgerEntry> journalEntryRows = await _context.LedgerEntries.Where(le => le.JournalEntryId == JournalEntryId).ToListAsync();
            int rowIndex = 0;
            foreach (LedgerEntry le in journalEntryRows)
            {
                rows[rowIndex] = new JournalViewModelRow();
                rows[rowIndex].AccountNumber = le.Account.AccountNumber.ToString();

Views/JournalEntries/Create.cshtml
@using AccountingApp.ViewModels;
@model JournalEntryViewModel



<form asp-controller="JournalEntries" asp-action="Create" id="JournalForm" method="post">
    <div>
        <label name="yearLabel">Välj bokföringsår</label>
        <select id="AccountingYear" asp-for="SelectedAccountingYear" asp-items="@Model.AccountingYearsList" onchange="ChangeYear(this)"></select>
    </div>
    <div>
        <label name="dateLabel">Välj bokföringsdatum</label>
        <input asp-for="SelectedDate" type="date" value="@DateTime.Today.ToShortDateString()" />
    </div>
    <div>
        <label>Välj journal</label>
        <select id="JournalSelect" asp-for="SelectedJournal" asp-items="@Model.JournalsList"></select>
    </div>
    <div>
        <label>Verifikationstext:</label>
        <input asp-for="Text" type="text" />
    </div>
    <table>
        <thead>
            <tr>
                <th colspan="2">Konto</th>
                <th>Debit</th>
                <th>Kredit</th>
            </tr>
        </thead>
        <tbody id="JournalFormBody">

            @for (int i = 0; i < 100; i++)
            {
                <tr id="Row_@i" class="d-none">
                    <td>
                        <input asp-for="Rows[i].AccountNumber" type="text" onchange="SelectAccount(this, @i)" />

                    </td>
                    <td>
                        <label id="Rows_AccountName__@i">Kontonamn</label>
                    </td>
                    <td>
                        <input asp-for="Rows[i].Debit" onchange="ValidateRow(this, @i)" type="text" />
                    </td>
                    <td>
                        <input asp-for="Rows[i].Credit" onchange="ValidateRow(this, @i)" type="text" />
                    </td>

                    <td>
                        <input type="button" onclick="RemoveRow(this, @i)" value="Ta bort" />
                    </td>
                    <td>
                        <label id="Rows_Warning_@i"></label>
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="2"><label id="SumLabel">Summa</label></td>
                <td><label id="DebitSum"></label></td>
                <td><label id="CreditSum"></label></td>

            </tr>
            <tr>
                <td>
                    <input type="button" name="AddRowButton" onclick="AddRowButtonClicked(this)" value="+" />
                </td>
            </tr>
            <tr>
                <td>
                    <input asp-for="RowsUsed" type="hidden" value="0" />
                    <input type="submit" asp-route-companyId="@Model.Company.Id" name="SubmitFormButton" value="Bokför" />
                </td>
            </tr>
        </tfoot>
    </table>
</form>

<script>
    //Get list of accounts for account searching
    const Accounts = JSON.parse('@Html.Raw(Json.Serialize(Model.Accounts))');
    let AccountSearchSource = [];

    for (let key in Accounts) {
        AccountSearchSource.push({ 'label': key + " - "+ Accounts[key], 'value': key });
    }

    for (let i = 0; i < 100; i++) {
        $("#Rows_" + i + "__AccountNumber").autocomplete({ source: AccountSearchSource });
    }

    //Set index of rows visible
    let NumberOfRows = 0;

    //Show 2 rows when starting
    for (let i = 0; i < 2; i++) {
        let rowToShowId = "#Row_" + NumberOfRows;
        AddRowButtonClicked($(rowToShowId))
    }

    //Parse AccountingYears
    let Years = JSON.parse('@Html.Raw(Json.Serialize(Model.AccountingYears))');

    //Limit start & end date for datepicker
    $("#SelectedDate").attr({ "min": '@Model.SelectedAccountingYearStartDate.ToShortDateString()' });
    $("#SelectedDate").attr({ "max": '@Model.SelectedAccountingYearEndDate.ToShortDateString()' });

    //Validate();
    //Shows a new row
    function AddRowButtonClicked(object) {

        console.log("Add row button clicked:" + object.value)
        console.log("Number of rows before:" + NumberOfRows);
        let rowToShowId = "#Row_" + NumberOfRows;

        $(rowToShowId).toggleClass('d-none');
        $("#RowsUsed").val(NumberOfRows);
        ValidateRow($(rowToShowId), NumberOfRows);
        NumberOfRows++;
        $("#RowsUsed").val(NumberOfRows);
        console.log("Number of rows after:" + NumberOfRows);
        UpdateSum();
        
    }

    //Check if current value exists as key in Accounts, populate account_name label for row
    function SelectAccount(object, row) {
        let currentRowName = "#Rows_AccountName__" + row;
        let currentValue = $("#Rows_" + row + "__AccountNumber").val();
        console.log(currentRowName + " - " + currentValue + " - " + Accounts[currentValue])
        if (Accounts[currentValue] !== null) {
            $(currentRowName).text(Accounts[currentValue]);
        }
    }

    //Changes min & max of datepicker when selecting accounting year
    function ChangeYear(object) {
        const yearValue = object.value;

        for (let y = 0; y < Years.length; y++) {
            //console.log(yearValue + " " + (Years[y]['id'] == yearValue));
            if (Years[y]['id'] == yearValue) {
                let minDate = new Date(Years[y]['startDate']);
                let maxDate = new Date(Years[y]['endDate'])

                $("#SelectedDate").attr({ "min": minDate.toLocaleDateString() });
                $("#SelectedDate").attr({ "max": maxDate.toLocaleDateString()});
                console.log($("#SelectedDate").attr('min'));
                console.log($("#SelectedDate").attr('max'));
            }
        }
    }

    //Moves every row below up one and clears and hides the last row
    function RemoveRow(object, row) {
        console.log("Remove row button clicked :" + row + " - " + object.value);
        console.log("Number of rows before:" + NumberOfRows);
        for (let i = row; i < NumberOfRows; i++) {

            $("#Rows_" + i + "__AccountNumber").val($("#Rows_" + (i + 1) + "__AccountNumber").val());
            SelectAccount($("#Rows_" + i + "__AccountNumber"), i);

            $("#Rows_" + i + "__Credit").val($("#Rows_" + (i + 1) + "__Credit").val());
            $("#Rows_" + i + "__Credit").val($("#Rows_" + (i + 1) + "__Debit").val());
        }
        NumberOfRows--;
        //Clear values in last row
        $("#Rows_" + NumberOfRows + "__AccountNumber").val("");
        SelectAccount($("#Rows_" + NumberOfRows + "__AccountNumber"), NumberOfRows);
        $("#Rows_" + NumberOfRows + "__Credit").val("");
        $("#Rows_" + NumberOfRows + "__Debit").val("");
        //Hide last row
        $("#Row_" + NumberOfRows).toggleClass('d-none');
     
        $("#RowsUsed").val(NumberOfRows);
        console.log("Number of rows after:" + NumberOfRows);
        UpdateSum();
    }

    //Loops through visible rows and sums Credit, Debit columns
    function UpdateSum() {
        let creditSum = 0;
        let debitSum = 0;

        for (let i = 0; i <= NumberOfRows; i++) {
            //Handle ',' as decimal sign

            let rowDebit = parseFloat($("#Rows_" + i + "__Debit").val().replace(',', '.'));
            let rowCredit = parseFloat($("#Rows_" + i + "__Credit").val().replace(',', '.'));

            rowDebit = $.isNumeric(rowDebit) ? rowDebit : 0;
            rowCredit = $.isNumeric(rowCredit) ? rowCredit : 0;

            debitSum += rowDebit;
            creditSum += rowCredit;
        }
        if (debitSum === creditSum)
            $("#SumLabel").css('color', 'green');
        else
            $("#SumLabel").css('color', 'red');
        $("#DebitSum").text(debitSum);
        $("#CreditSum").text(creditSum);
        //Validate();
    }

    function ValidateRow(object, row) {
        let validateText = "";
        //Validate account number
        let accountNumber = $("#Rows_" + row + "__AccountNumber").val();

        if (Accounts[accountNumber] == undefined)
            validateText += "Konto saknas! ";

        // Can only use either debit or credit field so empty other one
        if (object.id == "Rows_" + row + "__Debit")
            $("#Rows_" + row + "__Credit").val("");
        else if (object.id == "Rows_" + row + "__Credit")
            $("#Rows_" + row + "__Debit").val("");


        $("#Rows_Warning_" + row).text(validateText);
        UpdateSum(); //Finally update sums
    }

    function Validate() {
        let validated = true;
        //Check row warnings
        for (let i = 0; i < NumberOfRows; i++) {
            if ($("#Rows_Warning_" + i).text !== "") {
                validated = false;
            }                         
        }

        if ($("#DebitSum").text() != $("#CreditSum").text()) {
            validated = false;
        }

        if (validated) {
            console.log("Enable button");
            $("#SubmitFormButton").prop("disabled", false);
        }
        else {
            console.log("Disable button");
            $("#SubmitFormButton").prop("disabled", true);
        }

    }
</script>

Views/JournalEntries/Delete.cshtml
@model AccountingApp.Models.JournalEntry

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>JournalEntry</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/JournalEntries/Details.cshtml
@using AccountingApp.ViewModels;
@model JournalEntriesDetailViewModel
@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>JournalEntry</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.JournalEntry.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.JournalEntry.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.JournalEntry.Active)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.JournalEntry.Active)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.JournalEntry.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.JournalEntry.Name)
        </dd>
    </dl>
</div>
<div>
    <table>
        <thead>
            <tr>
                <th colspan="2">Konto</th>
                <th>Debit</th>
                <th>Kredit</th>

            </tr>
        </thead>
        <tbody>
            @foreach (JournalEntriesDetailViewModelRow row in Model.Rows)
            {
                <tr>
                    <td>
                        @row.AccountNumber
                    </td>
                    <td>
                        @row.AccountName
                    </td>
                    <td>
                        @row.Debit
                    </td>
                    <td>
                        @row.Credit
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="2">
                    Summa
                </td>
                <td>
                    @Model.DebitSum
                </td>
                <td>
                    @Model.CreditSum
                </td>
            </tr>
        </tfoot>
    </table>
</div>
<div>
    <a asp-controller="Companies" asp-action="CompanySelector">Åter till bokföring</a>
    @*TODO: Länka direkt till bokföringsview*@
</div>

Views/JournalEntries/Export.cshtml
@using AccountingApp.ViewModels
@model  ExportViewModel
<form asp-controller="JournalEntries" asp-action="Download" method="post">
    <label>Välj bokföringsår att exportera</label>
    <select asp-for="@Model.SelectedAccountingYear" asp-items="@Model.AccountingYearsSelectListItems"></select>
    <input type="hidden" asp-for="@Model.CompanyId" value="@Model.CompanyId" />
    <button type="submit">Exportera</button>
</form>

Views/JournalEntries/Index.cshtml
@model IEnumerable<AccountingApp.ViewModels.JournalEntriesListViewModel>

@{
    ViewData["Title"] = "Lista verifikat";
}

<h1>Lista verifikat</h1>

@*TODO: Make Each item collapsible bootstrap accordian*@
@foreach (var item in Model)
{

    <p>
        <a asp-action="Edit" asp-controller="JournalEntries" asp-route-id="@item.JournalEntry.Id">@item.JournalEntry.Id - @item.JournalEntry.Name - @item.JournalEntry.Date.ToShortDateString() </a> |
    </p>
    <table>
        <thead>
            <tr>
                <th colspan="2">Konto</th>
                <th>Debit</th>
                <th>Kredit</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var row in item.Rows)
            {
                <tr>
                    <td>
                        @row.AccountNumber
                    </td>
                    <td>
                        @row.AccountName
                    </td>
                    <td>
                        @row.Debit
                    </td>
                    <td>
                        @row.Credit
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="2">
                    Summa
                </td>
                <td>
                    @item.DebitSum
                </td>
                <td>
                    @item.CreditSum
                </td>
            </tr>
        </tfoot>
    </table>
}

Views/JournalEntries/Report.cshtml
@using AccountingApp.ViewModels
@model ReportViewModel


@foreach (AccountingYear year in Model.Reports.Keys)
{
    <div class="card">
        <h2>@year.StartDate.ToShortDateString() - @year.EndDate.ToShortDateString()</h2>

        @foreach (IGrouping<string, Account> accountGrouping in Model.Accounts.GroupBy(a => a.AccountClassName))
        {
            double accountClassSum = 0;
    <div class="card-body">
        <div class="card-header">@accountGrouping.Key</div>
        <div class="card-body">
            <table class="table table-bordered table-responsive-sm">
                <thead>
                    <tr>
                        <th colspan="2">Konto</th>
                        <th>Saldo</th>
                    </tr>
                </thead>
                @{
                    double accountGroupSum = 0;
                }
                <tbody>
                    @foreach (Account account in accountGrouping)
                    {
                        @if (@Model.Reports[year].LedgerEntriesPerAccount.ContainsKey(account))
                        {
                            <tr>
                                <td>@account.AccountNumber</td>
                                <td> @account.Name </td>
                                <td>@Model.Reports[year].LedgerEntriesPerAccount[account].Sum(le => le.Value)</td>
                                @{
                                    accountGroupSum += Model.Reports[year].LedgerEntriesPerAccount[account].Sum(le => le.Value);
                                    accountClassSum += Model.Reports[year].LedgerEntriesPerAccount[account].Sum(le => le.Value);
                                }
                            </tr>
                        }
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="2">Summa</td>
                        <td> @accountGroupSum</td>
                    </tr>
                </tfoot>
            </table>
        </div>
        <div class="card-footer"><div class="row"><div class="col-2">Summa</div><div class="col-2">@accountClassSum</div></div></div>
    </div>
        }
    </div>
}

Views/JournalEntries/Submit.cshtml
@using AccountingApp.ViewModels;
@model SubmitViewModel

<h3><label asp-for="Status">@Model.Status</label></h3>
<h2><a asp-controller="JournalEntries" asp-action="Details" asp-route-Id="@Model.JournalEntryId">Se verifikat</a></h2>
<h2><a asp-controller="JournalEntries" asp-action="Create" asp-route-Id="@Model.CompanyId">Nytt verifikat</a></h2>