Models/Company.cs
using System.Collections.Generic;


namespace AccountingApp.Models
{
    public class Company
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string OfficialId { get; set; }
        public List<AccountingYear> AccountingYears { get; set; }
        public List<Account> Accounts { get; set; }
        public List<Journal> Journals { get; set; }
        public List<JournalEntry> Transactions { get; set; }
  
    }
}

ViewModels/CompanySelectorViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccountingApp.Models;
using AccountingApp.Data;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AccountingApp.ViewModels
{
    public class CompanySelectorViewModel
    {
        public List<Company> Companies { get; set; }

        public Company SelectedCompany { get; set; }

    }
}

Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AccountingApp.Data;
using AccountingApp.Models;
using AccountingApp.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;

namespace AccountingApp.Controllers
{
    [Authorize]
    public class CompaniesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private IWebHostEnvironment _environment;
        private readonly string rootPath;

        public CompaniesController(ApplicationDbContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
            rootPath = environment.WebRootPath;
        }

        // GET: Companies
        public async Task<IActionResult> Index()
        {
            string userName = HttpContext.User.Identity.Name;
            List<int> companies = await _context.UserCompanies.Where(uc => uc.UserName == userName).Select(c=>c.CompanyId).ToListAsync();
            return View(await _context.Companies.Where(c => companies.Contains(c.Id)).ToListAsync());
        }

        public async Task<IActionResult> CompanySelector()
        {          
            string userName = HttpContext.User.Identity.Name;
            List<int> companyIds = await _context.UserCompanies.Where(uc => uc.UserName == userName).Select(c => c.CompanyId).ToListAsync();
            List<Company> companies = await _context.Companies.Where(c => companyIds.Contains(c.Id)).ToListAsync();
            CompanySelectorViewModel viewModel = new CompanySelectorViewModel
            {
                Companies = companies
            };
            return View(viewModel);
        }

        // GET: Companies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var company = await _context.Companies
                .FirstOrDefaultAsync(m => m.Id == id);
            if (company == null)
            {
                return NotFound();
            }

            List<AccountingYear> years = await _context.AccountingYears.Where(ay => ay.CompanyId == id).OrderBy(ay => ay.StartDate).ToListAsync();
            List<Journal> journals = await _context.Journals.Where(j => j.CompanyId == id).ToListAsync();

            return View(new CompanyDetailsViewModel { Company = company, AccountingYears = years, Journals = journals});
        }

        // GET: Companies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Companies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,OfficialId")] Company company, DateTime accountingYearStart, DateTime accountingYearEnd)
        {
            if (ModelState.IsValid)
            {
                _context.Add(company);
                await _context.SaveChangesAsync();
                SetupCompanyData(company, accountingYearStart, accountingYearEnd);
                await _context.SaveChangesAsync();
                _context.UserCompanies.Add(new UserCompany { CompanyId = company.Id, UserName = HttpContext.User.Identity.Name });
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(company);
        }

        /// <summary>
        /// Imports default accounts with grouping and classes, adds main journal and first accounting year
        /// </summary>
        /// <param name="company"></param>
        private void SetupCompanyData(Company company, DateTime start, DateTime end)
        {          
            AddAccounts(_context, company);
            _context.SaveChanges();
    
            _context.Journals.Add(new Journal { CompanyId = company.Id, Name = "Huvudbok", Active = true, JournalEntries = new List<JournalEntry>() });
            _context.AccountingYears.Add(new AccountingYear { CompanyId = company.Id, StartDate = start, EndDate = end });
            _context.SaveChanges();
        }

        // GET: Companies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var company = await _context.Companies.FindAsync(id);
            if (company == null)
            {
                return NotFound();
            }
            return View(company);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,OfficialId")] Company company)
        {
            if (id != company.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(company);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompanyExists(company.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(company);
        }

        // GET: Companies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var company = await _context.Companies
                .FirstOrDefaultAsync(m => m.Id == id);
            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var company = await _context.Companies.FindAsync(id);

            //Delete journals, journalentry,  ledgerentry
            List<Journal> journals = await _context.Journals.Include(j => j.JournalEntries).Where(j => j.CompanyId == id).ToListAsync();
            foreach (Journal j in journals)
            {
                List<JournalEntry> journalEntries = await _context.JournalEntry.Where(je => je.JournalId == j.Id).ToListAsync();
                foreach (JournalEntry je in journalEntries)
                {
                    List<LedgerEntry> ledgerEntries = await _context.LedgerEntries.Where(le => le.JournalEntryId == je.Id).ToListAsync();
                    foreach (LedgerEntry le in ledgerEntries)
                        _context.LedgerEntries.Remove(le);
                    _context.JournalEntry.Remove(je);
                }
                _context.Journals.Remove(j);
                await _context.SaveChangesAsync();
            }
            //Accounts
            List<Account> accounts = await _context.Accounts.Where(a => a.CompanyId == id).ToListAsync();
            foreach (Account a in accounts)
            {
                _context.Accounts.Remove(a);
            }
            await _context.SaveChangesAsync();

            //Accounting years
            List<AccountingYear> accountingYears = await _context.AccountingYears.Where(ay => ay.CompanyId == id).ToListAsync();
            foreach (AccountingYear ay in accountingYears)
                _context.AccountingYears.Remove(ay);
            await _context.SaveChangesAsync();

            //User company link
            List<UserCompany> userCompanies = await _context.UserCompanies.Where(uc => uc.CompanyId == id).ToListAsync();
            foreach (UserCompany uc in userCompanies)
                _context.UserCompanies.Remove(uc);
             await _context.SaveChangesAsync();

            _context.Companies.Remove(company);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompanyExists(int id)
        {
            return _context.Companies.Any(e => e.Id == id);
        }

        private  void AddAccounts(ApplicationDbContext dbContext, Company company)
        {
            string[] accountLines = System.IO.File.ReadAllLines(rootPath +"/csv/konton.csv");
         
            //Id;Name;AccountClassNumber;AccountClassName;AccountGroupNumber;AccountGroupName;Standard

            for (int i = 1; i < accountLines.Length; i++)
            {
                string[] split = accountLines[i].Split(";");

                int accountClassNumber = int.Parse(split[2]);
                string accountClassName = split[3];
                int accountGroupNumber = int.Parse(split[4]);
                string accountGroupName = split[5];


                int id = int.Parse(split[0]);
                string name = split[1];
                bool standard = bool.Parse(split[6]);

                dbContext.Accounts.Add(new Account { CompanyId = company.Id, AccountNumber = id, Name = name,AccountClassNumber = accountClassNumber, AccountClassName = accountClassName, AccountGroupNumber = accountGroupNumber,AccountGroupName = accountGroupName, Standard = standard, Used = false });
                Console.WriteLine("Added " + split);

            }
        }

       

       

Controllers/JournalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AccountingApp.Data;
using AccountingApp.Models;

namespace AccountingApp.Controllers
{
    public class JournalsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public JournalsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Journals
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Journals.Include(j => j.Company);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Journals/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var journal = await _context.Journals
                .Include(j => j.Company)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (journal == null)
            {
                return NotFound();
            }

            return View(journal);
        }

        // GET: Journals/Create
        public IActionResult Create()
        {
            string userName = HttpContext.User.Identity.Name;
            List<int> companies =  _context.UserCompanies.Where(uc => uc.UserName == userName).Select(c => c.CompanyId).ToList();
            ViewData["CompanyId"] = new SelectList(_context.Companies.Where(c => companies.Contains(c.Id)), "Id", "Id");
            return View();
        }

        // POST: Journals/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CompanyId,Name,Active")] Journal journal)
        {
            if (ModelState.IsValid)
            {
                _context.Add(journal);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Id", journal.CompanyId);
            return View(journal);
        }

        // GET: Journals/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var journal = await _context.Journals.FindAsync(id);
            if (journal == null)
            {
                return NotFound();
            }
            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Id", journal.CompanyId);
            return View(journal);
        }

        // POST: Journals/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CompanyId,Name,Active")] Journal journal)
        {
            if (id != journal.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(journal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JournalExists(journal.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Id", journal.CompanyId);
            return View(journal);
        }

        // GET: Journals/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var journal = await _context.Journals
                .Include(j => j.Company)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (journal == null)
            {
                return NotFound();
            }

            return View(journal);
        }

        // POST: Journals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var journal = await _context.Journals.FindAsync(id);
            _context.Journals.Remove(journal);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool JournalExists(int id)
        {
            return _context.Journals.Any(e => e.Id == id);
        }
    }
}

Views/Companies/CompanySelector.cshtml
@using AccountingApp.ViewModels
@model CompanySelectorViewModel


@foreach (Company c in Model.Companies)
{
    <h3>@c.Name</h3>
    <h4><a asp-controller="JournalEntries" asp-action="Create" asp-route-Id="@c.Id">Bokför</a></h4>
    <h4><a asp-controller="JournalEntries" asp-action="Report" asp-route-Id="@c.Id">Rapport</a></h4>
    <h4><a asp-controller="JournalEntries" asp-action="Export" asp-route-Id="@c.Id">Exportera bokföring</a></h4>
    <h4><a asp-controller="Companies" asp-action="Details" asp-route-id="@c.Id">Visa bolag</a></h4>

}
<hr />
<h3><a href="/Companies/Create">Skapa nytt bolag</a></h3>

Views/Companies/Create.cshtml
@model AccountingApp.Models.Company

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Company</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficialId" class="control-label"></label>
                <input asp-for="OfficialId" class="form-control" />
                <span asp-validation-for="OfficialId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Bokföringsår start</label>
                <input name="accountingYearStart" class="form-control" type="date" />
                <label class="control-label">Bokföringsår slut</label>
                <input name="accountingYearEnd" class="form-control" type="date" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Companies/Delete.cshtml
@model AccountingApp.Models.Company

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Company</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OfficialId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OfficialId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Companies/Details.cshtml
@model AccountingApp.ViewModels.CompanyDetailsViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Company</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Company.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Company.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Company.OfficialId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Company.OfficialId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Company.Id">Redigera</a> |
    <a asp-action="Index">Se lista</a>
</div>
<div>
    <h4>Bokföringsår</h4>
    <a asp-controller="AccountingYears" asp-action="Create" asp-route-companyId="@Model.Company.Id">Skapa bokföringsår</a>
    <table>
        <thead>
            <tr>
                <th>Från datum</th>
                <th>Till datum</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (AccountingYear year in Model.AccountingYears)
            {
                <tr>
                    <td>@year.StartDate.ToShortDateString()</td>
                    <td>@year.EndDate.ToShortDateString()</td>
                    <td><a asp-controller="AccountingYears" asp-action="Details" asp-route-id="@year.Id">Visa</a></td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div>
    <h4>Journal</h4>
    <a asp-controller="Journal" asp-action="Create" asp-route-companyId="@Model.Company.Id">Skapa journal</a>
    <table>
        <thead>
            <tr>
                <th>Namn</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (Journal journal in Model.Journals)
            {
                <tr>
                    <td>@journal.Name</td>
                    <td><a asp-controller="Journals" asp-action="Details" asp-route-id="@journal.Id">Visa</a></td>
                </tr>
            }
        </tbody>
    </table>
</div>

Views/Companies/Edit.cshtml
@model AccountingApp.Models.Company

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Company</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OfficialId" class="control-label"></label>
                <input asp-for="OfficialId" class="form-control" />
                <span asp-validation-for="OfficialId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Companies/Index.cshtml
@model IEnumerable<AccountingApp.Models.Company>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OfficialId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OfficialId)
            </td>
            <td>

                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>